


*******************************************************************
*                                                                 *
*              WELCOME TO OPERATING SYSTEM PROJECT               *
*                         Release 1.7                             *
*                                                                 *
*******************************************************************



Copyright (C) 1990  The Research Foundation of SUNY,
		    Michael Kifer and Scott S. Smolka

(see $HOME/LICENCE for terms and conditions)




================  Summary of Simulation Parameters  ===============

Intensity of New Process Creation               = 10
Average CPU Time per Process                    = 300
Overall Frequency of Events                     = 10
  Share of Memory Related Events                   = 3
  Share of I/O Related Events                      = 3
  Share of Resource Related Events                 = 3
  Share of Socket Related Events                   = 1
Socket simulation mode                             = stream and dgram
CPU Time Quantum                                = 150
Degree of Prepaging                             = 4
Memory Reference Pattern                        = random
Deadlock Handling Method                        = avoidance
Simulation Time                                 = 40000
Number of Snapshots                             = 4
Trace Switch                                    = off
Type of Run                                     = noninteractive



====================  Beginning of Simulation  ====================


CLOCK>    399#*** WARNING: SIMCORE>
		Idle CPU with non-empty ready queue.



                       S I M C O R E   P C B   T A B L E 
*****************************************************************************
*  PCB  Size  Created  Last dispatch  Last burst  Accum CPU  Status   Prior *
*---------------------------------------------------------------------------*
*    0  2634       20            397           1        227  waiting      0 *
*    1  5956      332            364           1          4  ready        0 *
*****************************************************************************

CLOCK>    400#*** WARNING: SIMCORE>
		Idle CPU with non-empty ready queue.



                       S I M C O R E   P C B   T A B L E 
*****************************************************************************
*  PCB  Size  Created  Last dispatch  Last burst  Accum CPU  Status   Prior *
*---------------------------------------------------------------------------*
*    0  2634       20            397           1        227  waiting      0 *
*    1  5956      332            364           1          4  ready        0 *
*****************************************************************************

CLOCK>    408#*** WARNING: SIMCORE>
		Idle CPU with non-empty ready queue.



                       S I M C O R E   P C B   T A B L E 
*****************************************************************************
*  PCB  Size  Created  Last dispatch  Last burst  Accum CPU  Status   Prior *
*---------------------------------------------------------------------------*
*    1  5956      332            364           1          4  ready        0 *
*****************************************************************************

CLOCK>    409#*** WARNING: SIMCORE>
		Idle CPU with non-empty ready queue.



                       S I M C O R E   P C B   T A B L E 
*****************************************************************************
*  PCB  Size  Created  Last dispatch  Last burst  Accum CPU  Status   Prior *
*---------------------------------------------------------------------------*
*    1  5956      332            364           1          4  ready        0 *
*****************************************************************************

CLOCK>    410#*** WARNING: SIMCORE>
		Idle CPU with non-empty ready queue.



                       S I M C O R E   P C B   T A B L E 
*****************************************************************************
*  PCB  Size  Created  Last dispatch  Last burst  Accum CPU  Status   Prior *
*---------------------------------------------------------------------------*
*    1  5956      332            364           1          4  ready        0 *
*****************************************************************************

CLOCK>    411#*** WARNING: SIMCORE>
		Idle CPU with non-empty ready queue.



                       S I M C O R E   P C B   T A B L E 
*****************************************************************************
*  PCB  Size  Created  Last dispatch  Last burst  Accum CPU  Status   Prior *
*---------------------------------------------------------------------------*
*    1  5956      332            364           1          4  ready        0 *
*****************************************************************************

CLOCK>    412#*** WARNING: SIMCORE>
		Idle CPU with non-empty ready queue.



                       S I M C O R E   P C B   T A B L E 
*****************************************************************************
*  PCB  Size  Created  Last dispatch  Last burst  Accum CPU  Status   Prior *
*---------------------------------------------------------------------------*
*    1  5956      332            364           1          4  ready        0 *
*****************************************************************************

CLOCK>    413#*** WARNING: SIMCORE>
		Idle CPU with non-empty ready queue.



                       S I M C O R E   P C B   T A B L E 
*****************************************************************************
*  PCB  Size  Created  Last dispatch  Last burst  Accum CPU  Status   Prior *
*---------------------------------------------------------------------------*
*    1  5956      332            364           1          4  ready        0 *
*****************************************************************************

CLOCK>    414#*** WARNING: SIMCORE>
		Idle CPU with non-empty ready queue.



                       S I M C O R E   P C B   T A B L E 
*****************************************************************************
*  PCB  Size  Created  Last dispatch  Last burst  Accum CPU  Status   Prior *
*---------------------------------------------------------------------------*
*    1  5956      332            364           1          4  ready        0 *
*****************************************************************************

CLOCK>    415#*** WARNING: SIMCORE>
		Idle CPU with non-empty ready queue.



                       S I M C O R E   P C B   T A B L E 
*****************************************************************************
*  PCB  Size  Created  Last dispatch  Last burst  Accum CPU  Status   Prior *
*---------------------------------------------------------------------------*
*    1  5956      332            364           1          4  ready        0 *
*****************************************************************************



	***  The following warning looks like a recurrent problem;
	***  it will be supressed till time = 10416.

CLOCK>    416#*** WARNING: SIMCORE>
		Idle CPU with non-empty ready queue.



                       S I M C O R E   P C B   T A B L E 
*****************************************************************************
*  PCB  Size  Created  Last dispatch  Last burst  Accum CPU  Status   Prior *
*---------------------------------------------------------------------------*
*    1  5956      332            364           1          4  ready        0 *
*****************************************************************************

CLOCK>  10000#*** WARNING: SIMCORE>
		PCB 9 is ready and starving for at least 7000 time units.
		Possible cause:
			- Due to error in CPU module,
			  was not inserted into ready queue.





                       S I M C O R E   P C B   T A B L E 
*****************************************************************************
*  PCB  Size  Created  Last dispatch  Last burst  Accum CPU  Status   Prior *
*---------------------------------------------------------------------------*
*    9  2694     2307             -1           0          0  ready        0 *
*    1  5956      332            364           1          4  ready        0 *
*    5  2026      940             -1           0          0  ready        0 *
*   15  4938     4976           5271           2        155  ready        0 *
*   10  5846     2707             -1           0          0  ready        0 *
*   12  1599     3662             -1           0          0  ready        0 *
*   13  3219     3773             -1           0          0  ready        0 *
*   14  6536     4159             -1           0          0  ready        0 *
*   27  5593     7253           7320           1         18  waiting      0 *
*   17  7940     5491             -1           0          0  ready        0 *
*   18  6460     5557             -1           0          0  ready        0 *
*   19  4361     5605             -1           0          0  ready        0 *
*   20  5809     5664             -1           0          0  ready        0 *
*   21  6582     5823             -1           0          0  ready        0 *
*   22  7582     5910             -1           0          0  ready        0 *
*   24  7858     6293             -1           0          0  ready        0 *
*   25  4333     6639             -1           0          0  ready        0 *
*   26   914     6663             -1           0          0  ready        0 *
*   28  2322     7518           8495           2        585  waiting      0 *
*   29  5028     8590           8761           2         79  waiting      0 *
*****************************************************************************



:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
::                                                               ::
::                  Snapshot at clock :  10000                   ::
::                                                               ::
:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::


              S I M C O R E   W A I T I N G   Q U E U E 
*****************************************************************************
* Event   PCB   IORB   File                  RRB    Rsrc   PRRB  SocketName *
*---------------------------------------------------------------------------*
*   407    28   none   none                 none    none      8  Xwindow    *
*   333    27   none   none                 none    none      6  talk.fun   *
*   416    29   none   none                 none    none      9  talk.alt   *
*****************************************************************************



                       S I M C O R E   P C B   T A B L E 
*****************************************************************************
*  PCB  Size  Created  Last dispatch  Last burst  Accum CPU  Status   Prior *
*---------------------------------------------------------------------------*
*    9  2694     2307             -1           0          0  ready        0 *
*    1  5956      332            364           1          4  ready        0 *
*    5  2026      940             -1           0          0  ready        0 *
*   15  4938     4976           5271           2        155  ready        0 *
*   10  5846     2707             -1           0          0  ready        0 *
*   12  1599     3662             -1           0          0  ready        0 *
*   13  3219     3773             -1           0          0  ready        0 *
*   14  6536     4159             -1           0          0  ready        0 *
*   27  5593     7253           7320           1         18  waiting      0 *
*   17  7940     5491             -1           0          0  ready        0 *
*   18  6460     5557             -1           0          0  ready        0 *
*   19  4361     5605             -1           0          0  ready        0 *
*   20  5809     5664             -1           0          0  ready        0 *
*   21  6582     5823             -1           0          0  ready        0 *
*   22  7582     5910             -1           0          0  ready        0 *
*   24  7858     6293             -1           0          0  ready        0 *
*   25  4333     6639             -1           0          0  ready        0 *
*   26   914     6663             -1           0          0  ready        0 *
*   28  2322     7518           8495           2        585  waiting      0 *
*   29  5028     8590           8761           2         79  waiting      0 *
*****************************************************************************



=====================  Summary of Statistics  ====================

Total num of processes created                            =    30
  Total num of processes terminated                             =    9
  Total num of processes killed                                 =    1
        num of processes in CPU ready queue                     =   17
        num of processes in event waiting queues                =    3

  Total num of wait requests                               =   97
  Total num of signals                                     =  226
  Total num of timer interrupts                            =  475

CPU time used                                        =  1609
CPU utilization                                      =     0.1609

Memory utilization                                   =     0.5129

System throughput ( x 1000 )                         =     0.9000
Average num of processes during simulation           =    10.4157
Average CPU time per process                         =   271.0667
Average waiting time per process                     =  3414.5667
Average turnaround time per process                  =  3471.9000




CLOCK>  10417#*** WARNING: SIMCORE>
		Idle CPU with non-empty ready queue.



                       S I M C O R E   P C B   T A B L E 
*****************************************************************************
*  PCB  Size  Created  Last dispatch  Last burst  Accum CPU  Status   Prior *
*---------------------------------------------------------------------------*
*    9  2694     2307             -1           0          0  ready        0 *
*    1  5956      332            364           1          4  ready        0 *
*    5  2026      940             -1           0          0  ready        0 *
*   15  4938     4976           5271           2        155  ready        0 *
*   10  5846     2707             -1           0          0  ready        0 *
*   12  1599     3662             -1           0          0  ready        0 *
*   13  3219     3773             -1           0          0  ready        0 *
*   14  6536     4159             -1           0          0  ready        0 *
*   27  5593     7253           7320           1         18  waiting      0 *
*   17  7940     5491             -1           0          0  ready        0 *
*   18  6460     5557             -1           0          0  ready        0 *
*   19  4361     5605             -1           0          0  ready        0 *
*   20  5809     5664             -1           0          0  ready        0 *
*   21  6582     5823             -1           0          0  ready        0 *
*   22  7582     5910             -1           0          0  ready        0 *
*   24  7858     6293             -1           0          0  ready        0 *
*   25  4333     6639             -1           0          0  ready        0 *
*   26   914     6663             -1           0          0  ready        0 *
*   28  2322     7518           8495           2        585  waiting      0 *
*   29  5028     8590           8761           2         79  waiting      0 *
*****************************************************************************

CLOCK>  10418#*** WARNING: SIMCORE>
		Idle CPU with non-empty ready queue.



                       S I M C O R E   P C B   T A B L E 
*****************************************************************************
*  PCB  Size  Created  Last dispatch  Last burst  Accum CPU  Status   Prior *
*---------------------------------------------------------------------------*
*    9  2694     2307             -1           0          0  ready        0 *
*    1  5956      332            364           1          4  ready        0 *
*    5  2026      940             -1           0          0  ready        0 *
*   15  4938     4976           5271           2        155  ready        0 *
*   10  5846     2707             -1           0          0  ready        0 *
*   12  1599     3662             -1           0          0  ready        0 *
*   13  3219     3773             -1           0          0  ready        0 *
*   14  6536     4159             -1           0          0  ready        0 *
*   27  5593     7253           7320           1         18  waiting      0 *
*   17  7940     5491             -1           0          0  ready        0 *
*   18  6460     5557             -1           0          0  ready        0 *
*   19  4361     5605             -1           0          0  ready        0 *
*   20  5809     5664             -1           0          0  ready        0 *
*   21  6582     5823             -1           0          0  ready        0 *
*   22  7582     5910             -1           0          0  ready        0 *
*   24  7858     6293             -1           0          0  ready        0 *
*   25  4333     6639             -1           0          0  ready        0 *
*   26   914     6663             -1           0          0  ready        0 *
*   28  2322     7518           8495           2        585  waiting      0 *
*   29  5028     8590           8761           2         79  waiting      0 *
*****************************************************************************

CLOCK>  10419#*** WARNING: SIMCORE>
		Idle CPU with non-empty ready queue.



                       S I M C O R E   P C B   T A B L E 
*****************************************************************************
*  PCB  Size  Created  Last dispatch  Last burst  Accum CPU  Status   Prior *
*---------------------------------------------------------------------------*
*    9  2694     2307             -1           0          0  ready        0 *
*    1  5956      332            364           1          4  ready        0 *
*    5  2026      940             -1           0          0  ready        0 *
*   15  4938     4976           5271           2        155  ready        0 *
*   10  5846     2707             -1           0          0  ready        0 *
*   12  1599     3662             -1           0          0  ready        0 *
*   13  3219     3773             -1           0          0  ready        0 *
*   14  6536     4159             -1           0          0  ready        0 *
*   27  5593     7253           7320           1         18  waiting      0 *
*   17  7940     5491             -1           0          0  ready        0 *
*   18  6460     5557             -1           0          0  ready        0 *
*   19  4361     5605             -1           0          0  ready        0 *
*   20  5809     5664             -1           0          0  ready        0 *
*   21  6582     5823             -1           0          0  ready        0 *
*   22  7582     5910             -1           0          0  ready        0 *
*   24  7858     6293             -1           0          0  ready        0 *
*   25  4333     6639             -1           0          0  ready        0 *
*   26   914     6663             -1           0          0  ready        0 *
*   28  2322     7518           8495           2        585  waiting      0 *
*   29  5028     8590           8761           2         79  waiting      0 *
*****************************************************************************

CLOCK>  10420#*** WARNING: SIMCORE>
		Idle CPU with non-empty ready queue.



                       S I M C O R E   P C B   T A B L E 
*****************************************************************************
*  PCB  Size  Created  Last dispatch  Last burst  Accum CPU  Status   Prior *
*---------------------------------------------------------------------------*
*    9  2694     2307             -1           0          0  ready        0 *
*    1  5956      332            364           1          4  ready        0 *
*    5  2026      940             -1           0          0  ready        0 *
*   15  4938     4976           5271           2        155  ready        0 *
*   10  5846     2707             -1           0          0  ready        0 *
*   12  1599     3662             -1           0          0  ready        0 *
*   13  3219     3773             -1           0          0  ready        0 *
*   14  6536     4159             -1           0          0  ready        0 *
*   27  5593     7253           7320           1         18  waiting      0 *
*   17  7940     5491             -1           0          0  ready        0 *
*   18  6460     5557             -1           0          0  ready        0 *
*   19  4361     5605             -1           0          0  ready        0 *
*   20  5809     5664             -1           0          0  ready        0 *
*   21  6582     5823             -1           0          0  ready        0 *
*   22  7582     5910             -1           0          0  ready        0 *
*   24  7858     6293             -1           0          0  ready        0 *
*   25  4333     6639             -1           0          0  ready        0 *
*   26   914     6663             -1           0          0  ready        0 *
*   28  2322     7518           8495           2        585  waiting      0 *
*   29  5028     8590           8761           2         79  waiting      0 *
*****************************************************************************

CLOCK>  10421#*** WARNING: SIMCORE>
		Idle CPU with non-empty ready queue.



                       S I M C O R E   P C B   T A B L E 
*****************************************************************************
*  PCB  Size  Created  Last dispatch  Last burst  Accum CPU  Status   Prior *
*---------------------------------------------------------------------------*
*    9  2694     2307             -1           0          0  ready        0 *
*    1  5956      332            364           1          4  ready        0 *
*    5  2026      940             -1           0          0  ready        0 *
*   15  4938     4976           5271           2        155  ready        0 *
*   10  5846     2707             -1           0          0  ready        0 *
*   12  1599     3662             -1           0          0  ready        0 *
*   13  3219     3773             -1           0          0  ready        0 *
*   14  6536     4159             -1           0          0  ready        0 *
*   27  5593     7253           7320           1         18  waiting      0 *
*   17  7940     5491             -1           0          0  ready        0 *
*   18  6460     5557             -1           0          0  ready        0 *
*   19  4361     5605             -1           0          0  ready        0 *
*   20  5809     5664             -1           0          0  ready        0 *
*   21  6582     5823             -1           0          0  ready        0 *
*   22  7582     5910             -1           0          0  ready        0 *
*   24  7858     6293             -1           0          0  ready        0 *
*   25  4333     6639             -1           0          0  ready        0 *
*   26   914     6663             -1           0          0  ready        0 *
*   28  2322     7518           8495           2        585  waiting      0 *
*   29  5028     8590           8761           2         79  waiting      0 *
*****************************************************************************

CLOCK>  10422#*** WARNING: SIMCORE>
		Idle CPU with non-empty ready queue.



                       S I M C O R E   P C B   T A B L E 
*****************************************************************************
*  PCB  Size  Created  Last dispatch  Last burst  Accum CPU  Status   Prior *
*---------------------------------------------------------------------------*
*    9  2694     2307             -1           0          0  ready        0 *
*    1  5956      332            364           1          4  ready        0 *
*    5  2026      940             -1           0          0  ready        0 *
*   15  4938     4976           5271           2        155  ready        0 *
*   10  5846     2707             -1           0          0  ready        0 *
*   12  1599     3662             -1           0          0  ready        0 *
*   13  3219     3773             -1           0          0  ready        0 *
*   14  6536     4159             -1           0          0  ready        0 *
*   27  5593     7253           7320           1         18  waiting      0 *
*   17  7940     5491             -1           0          0  ready        0 *
*   18  6460     5557             -1           0          0  ready        0 *
*   19  4361     5605             -1           0          0  ready        0 *
*   20  5809     5664             -1           0          0  ready        0 *
*   21  6582     5823             -1           0          0  ready        0 *
*   22  7582     5910             -1           0          0  ready        0 *
*   24  7858     6293             -1           0          0  ready        0 *
*   25  4333     6639             -1           0          0  ready        0 *
*   26   914     6663             -1           0          0  ready        0 *
*   28  2322     7518           8495           2        585  waiting      0 *
*   29  5028     8590           8761           2         79  waiting      0 *
*****************************************************************************

CLOCK>  10423#*** WARNING: SIMCORE>
		Idle CPU with non-empty ready queue.



                       S I M C O R E   P C B   T A B L E 
*****************************************************************************
*  PCB  Size  Created  Last dispatch  Last burst  Accum CPU  Status   Prior *
*---------------------------------------------------------------------------*
*    9  2694     2307             -1           0          0  ready        0 *
*    1  5956      332            364           1          4  ready        0 *
*    5  2026      940             -1           0          0  ready        0 *
*   15  4938     4976           5271           2        155  ready        0 *
*   10  5846     2707             -1           0          0  ready        0 *
*   12  1599     3662             -1           0          0  ready        0 *
*   13  3219     3773             -1           0          0  ready        0 *
*   14  6536     4159             -1           0          0  ready        0 *
*   27  5593     7253           7320           1         18  waiting      0 *
*   17  7940     5491             -1           0          0  ready        0 *
*   18  6460     5557             -1           0          0  ready        0 *
*   19  4361     5605             -1           0          0  ready        0 *
*   20  5809     5664             -1           0          0  ready        0 *
*   21  6582     5823             -1           0          0  ready        0 *
*   22  7582     5910             -1           0          0  ready        0 *
*   24  7858     6293             -1           0          0  ready        0 *
*   25  4333     6639             -1           0          0  ready        0 *
*   26   914     6663             -1           0          0  ready        0 *
*   28  2322     7518           8495           2        585  waiting      0 *
*   29  5028     8590           8761           2         79  waiting      0 *
*****************************************************************************

CLOCK>  10424#*** WARNING: SIMCORE>
		Idle CPU with non-empty ready queue.



                       S I M C O R E   P C B   T A B L E 
*****************************************************************************
*  PCB  Size  Created  Last dispatch  Last burst  Accum CPU  Status   Prior *
*---------------------------------------------------------------------------*
*    9  2694     2307             -1           0          0  ready        0 *
*    1  5956      332            364           1          4  ready        0 *
*    5  2026      940             -1           0          0  ready        0 *
*   15  4938     4976           5271           2        155  ready        0 *
*   10  5846     2707             -1           0          0  ready        0 *
*   12  1599     3662             -1           0          0  ready        0 *
*   13  3219     3773             -1           0          0  ready        0 *
*   14  6536     4159             -1           0          0  ready        0 *
*   27  5593     7253           7320           1         18  waiting      0 *
*   17  7940     5491             -1           0          0  ready        0 *
*   18  6460     5557             -1           0          0  ready        0 *
*   19  4361     5605             -1           0          0  ready        0 *
*   20  5809     5664             -1           0          0  ready        0 *
*   21  6582     5823             -1           0          0  ready        0 *
*   22  7582     5910             -1           0          0  ready        0 *
*   24  7858     6293             -1           0          0  ready        0 *
*   25  4333     6639             -1           0          0  ready        0 *
*   26   914     6663             -1           0          0  ready        0 *
*   28  2322     7518           8495           2        585  waiting      0 *
*   29  5028     8590           8761           2         79  waiting      0 *
*****************************************************************************

CLOCK>  10425#*** WARNING: SIMCORE>
		Idle CPU with non-empty ready queue.



                       S I M C O R E   P C B   T A B L E 
*****************************************************************************
*  PCB  Size  Created  Last dispatch  Last burst  Accum CPU  Status   Prior *
*---------------------------------------------------------------------------*
*    9  2694     2307             -1           0          0  ready        0 *
*    1  5956      332            364           1          4  ready        0 *
*    5  2026      940             -1           0          0  ready        0 *
*   15  4938     4976           5271           2        155  ready        0 *
*   10  5846     2707             -1           0          0  ready        0 *
*   12  1599     3662             -1           0          0  ready        0 *
*   13  3219     3773             -1           0          0  ready        0 *
*   14  6536     4159             -1           0          0  ready        0 *
*   27  5593     7253           7320           1         18  waiting      0 *
*   17  7940     5491             -1           0          0  ready        0 *
*   18  6460     5557             -1           0          0  ready        0 *
*   19  4361     5605             -1           0          0  ready        0 *
*   20  5809     5664             -1           0          0  ready        0 *
*   21  6582     5823             -1           0          0  ready        0 *
*   22  7582     5910             -1           0          0  ready        0 *
*   24  7858     6293             -1           0          0  ready        0 *
*   25  4333     6639             -1           0          0  ready        0 *
*   26   914     6663             -1           0          0  ready        0 *
*   28  2322     7518           8495           2        585  waiting      0 *
*   29  5028     8590           8761           2         79  waiting      0 *
*****************************************************************************

CLOCK>  10426#*** WARNING: SIMCORE>
		Idle CPU with non-empty ready queue.



                       S I M C O R E   P C B   T A B L E 
*****************************************************************************
*  PCB  Size  Created  Last dispatch  Last burst  Accum CPU  Status   Prior *
*---------------------------------------------------------------------------*
*    9  2694     2307             -1           0          0  ready        0 *
*    1  5956      332            364           1          4  ready        0 *
*    5  2026      940             -1           0          0  ready        0 *
*   15  4938     4976           5271           2        155  ready        0 *
*   10  5846     2707             -1           0          0  ready        0 *
*   12  1599     3662             -1           0          0  ready        0 *
*   13  3219     3773             -1           0          0  ready        0 *
*   14  6536     4159             -1           0          0  ready        0 *
*   27  5593     7253           7320           1         18  waiting      0 *
*   17  7940     5491             -1           0          0  ready        0 *
*   18  6460     5557             -1           0          0  ready        0 *
*   19  4361     5605             -1           0          0  ready        0 *
*   20  5809     5664             -1           0          0  ready        0 *
*   21  6582     5823             -1           0          0  ready        0 *
*   22  7582     5910             -1           0          0  ready        0 *
*   24  7858     6293             -1           0          0  ready        0 *
*   25  4333     6639             -1           0          0  ready        0 *
*   26   914     6663             -1           0          0  ready        0 *
*   28  2322     7518           8495           2        585  waiting      0 *
*   29  5028     8590           8761           2         79  waiting      0 *
*****************************************************************************



	***  The following warning looks like a recurrent problem;
	***  it will be supressed till time = 20427.

CLOCK>  10427#*** WARNING: SIMCORE>
		Idle CPU with non-empty ready queue.



                       S I M C O R E   P C B   T A B L E 
*****************************************************************************
*  PCB  Size  Created  Last dispatch  Last burst  Accum CPU  Status   Prior *
*---------------------------------------------------------------------------*
*    9  2694     2307             -1           0          0  ready        0 *
*    1  5956      332            364           1          4  ready        0 *
*    5  2026      940             -1           0          0  ready        0 *
*   15  4938     4976           5271           2        155  ready        0 *
*   10  5846     2707             -1           0          0  ready        0 *
*   12  1599     3662             -1           0          0  ready        0 *
*   13  3219     3773             -1           0          0  ready        0 *
*   14  6536     4159             -1           0          0  ready        0 *
*   27  5593     7253           7320           1         18  waiting      0 *
*   17  7940     5491             -1           0          0  ready        0 *
*   18  6460     5557             -1           0          0  ready        0 *
*   19  4361     5605             -1           0          0  ready        0 *
*   20  5809     5664             -1           0          0  ready        0 *
*   21  6582     5823             -1           0          0  ready        0 *
*   22  7582     5910             -1           0          0  ready        0 *
*   24  7858     6293             -1           0          0  ready        0 *
*   25  4333     6639             -1           0          0  ready        0 *
*   26   914     6663             -1           0          0  ready        0 *
*   28  2322     7518           8495           2        585  waiting      0 *
*   29  5028     8590           8761           2         79  waiting      0 *
*****************************************************************************

CLOCK>  20000#*** WARNING: SIMCORE>
		PCB 9 is ready and starving for at least 7000 time units.
		Possible cause:
			- Due to error in CPU module,
			  was not inserted into ready queue.





                       S I M C O R E   P C B   T A B L E 
*****************************************************************************
*  PCB  Size  Created  Last dispatch  Last burst  Accum CPU  Status   Prior *
*---------------------------------------------------------------------------*
*    9  2694     2307             -1           0          0  ready        0 *
*    1  5956      332            364           1          4  ready        0 *
*    5  2026      940             -1           0          0  ready        0 *
*   15  4938     4976           5271           2        155  ready        0 *
*   10  5846     2707             -1           0          0  ready        0 *
*   12  1599     3662             -1           0          0  ready        0 *
*   13  3219     3773             -1           0          0  ready        0 *
*   14  6536     4159             -1           0          0  ready        0 *
*   27  5593     7253           7320           1         18  ready        0 *
*   17  7940     5491             -1           0          0  ready        0 *
*   18  6460     5557             -1           0          0  ready        0 *
*   19  4361     5605             -1           0          0  ready        0 *
*   20  5809     5664             -1           0          0  ready        0 *
*   21  6582     5823             -1           0          0  ready        0 *
*   22  7582     5910             -1           0          0  ready        0 *
*   24  7858     6293             -1           0          0  ready        0 *
*   25  4333     6639             -1           0          0  ready        0 *
*   26   914     6663             -1           0          0  ready        0 *
*   28  2322     7518           8495           2        585  waiting      0 *
*   29  5028     8590           8761           2         79  waiting      0 *
*   32  2297    15248          15711           1        304  waiting      0 *
*   33  7083    15606             -1           0          0  ready        0 *
*****************************************************************************



:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
::                                                               ::
::                  Snapshot at clock :  20000                   ::
::                                                               ::
:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::


              S I M C O R E   W A I T I N G   Q U E U E 
*****************************************************************************
* Event   PCB   IORB   File                  RRB    Rsrc   PRRB  SocketName *
*---------------------------------------------------------------------------*
*   470    32   none   none                  155       3   none  none       *
*   407    28   none   none                 none    none      8  Xwindow    *
*   416    29   none   none                 none    none      9  talk.alt   *
*****************************************************************************



                       S I M C O R E   P C B   T A B L E 
*****************************************************************************
*  PCB  Size  Created  Last dispatch  Last burst  Accum CPU  Status   Prior *
*---------------------------------------------------------------------------*
*    9  2694     2307             -1           0          0  ready        0 *
*    1  5956      332            364           1          4  ready        0 *
*    5  2026      940             -1           0          0  ready        0 *
*   15  4938     4976           5271           2        155  ready        0 *
*   10  5846     2707             -1           0          0  ready        0 *
*   12  1599     3662             -1           0          0  ready        0 *
*   13  3219     3773             -1           0          0  ready        0 *
*   14  6536     4159             -1           0          0  ready        0 *
*   27  5593     7253           7320           1         18  ready        0 *
*   17  7940     5491             -1           0          0  ready        0 *
*   18  6460     5557             -1           0          0  ready        0 *
*   19  4361     5605             -1           0          0  ready        0 *
*   20  5809     5664             -1           0          0  ready        0 *
*   21  6582     5823             -1           0          0  ready        0 *
*   22  7582     5910             -1           0          0  ready        0 *
*   24  7858     6293             -1           0          0  ready        0 *
*   25  4333     6639             -1           0          0  ready        0 *
*   26   914     6663             -1           0          0  ready        0 *
*   28  2322     7518           8495           2        585  waiting      0 *
*   29  5028     8590           8761           2         79  waiting      0 *
*   32  2297    15248          15711           1        304  waiting      0 *
*   33  7083    15606             -1           0          0  ready        0 *
*****************************************************************************



=====================  Summary of Statistics  ====================

Total num of processes created                            =    34
  Total num of processes terminated                             =   11
  Total num of processes killed                                 =    1
        num of processes in CPU ready queue                     =   19
        num of processes in event waiting queues                =    3

  Total num of wait requests                               =  107
  Total num of signals                                     =  257
  Total num of timer interrupts                            =  546

CPU time used                                        =  1855
CPU utilization                                      =     0.0927

Memory utilization                                   =     0.7250

System throughput ( x 1000 )                         =     0.5500
Average num of processes during simulation           =    15.6806
Average CPU time per process                         =   258.3235
Average waiting time per process                     =  9165.7059
Average turnaround time per process                  =  9223.8529




CLOCK>  20428#*** WARNING: SIMCORE>
		Idle CPU with non-empty ready queue.



                       S I M C O R E   P C B   T A B L E 
*****************************************************************************
*  PCB  Size  Created  Last dispatch  Last burst  Accum CPU  Status   Prior *
*---------------------------------------------------------------------------*
*    9  2694     2307             -1           0          0  ready        0 *
*    1  5956      332            364           1          4  ready        0 *
*    5  2026      940             -1           0          0  ready        0 *
*   15  4938     4976           5271           2        155  ready        0 *
*   10  5846     2707             -1           0          0  ready        0 *
*   12  1599     3662             -1           0          0  ready        0 *
*   13  3219     3773             -1           0          0  ready        0 *
*   14  6536     4159             -1           0          0  ready        0 *
*   27  5593     7253           7320           1         18  ready        0 *
*   17  7940     5491             -1           0          0  ready        0 *
*   18  6460     5557             -1           0          0  ready        0 *
*   19  4361     5605             -1           0          0  ready        0 *
*   20  5809     5664             -1           0          0  ready        0 *
*   21  6582     5823             -1           0          0  ready        0 *
*   22  7582     5910             -1           0          0  ready        0 *
*   24  7858     6293             -1           0          0  ready        0 *
*   25  4333     6639             -1           0          0  ready        0 *
*   26   914     6663             -1           0          0  ready        0 *
*   28  2322     7518           8495           2        585  waiting      0 *
*   29  5028     8590           8761           2         79  waiting      0 *
*   32  2297    15248          15711           1        304  waiting      0 *
*   33  7083    15606             -1           0          0  ready        0 *
*****************************************************************************

CLOCK>  20429#*** WARNING: SIMCORE>
		Idle CPU with non-empty ready queue.



                       S I M C O R E   P C B   T A B L E 
*****************************************************************************
*  PCB  Size  Created  Last dispatch  Last burst  Accum CPU  Status   Prior *
*---------------------------------------------------------------------------*
*    9  2694     2307             -1           0          0  ready        0 *
*    1  5956      332            364           1          4  ready        0 *
*    5  2026      940             -1           0          0  ready        0 *
*   15  4938     4976           5271           2        155  ready        0 *
*   10  5846     2707             -1           0          0  ready        0 *
*   12  1599     3662             -1           0          0  ready        0 *
*   13  3219     3773             -1           0          0  ready        0 *
*   14  6536     4159             -1           0          0  ready        0 *
*   27  5593     7253           7320           1         18  ready        0 *
*   17  7940     5491             -1           0          0  ready        0 *
*   18  6460     5557             -1           0          0  ready        0 *
*   19  4361     5605             -1           0          0  ready        0 *
*   20  5809     5664             -1           0          0  ready        0 *
*   21  6582     5823             -1           0          0  ready        0 *
*   22  7582     5910             -1           0          0  ready        0 *
*   24  7858     6293             -1           0          0  ready        0 *
*   25  4333     6639             -1           0          0  ready        0 *
*   26   914     6663             -1           0          0  ready        0 *
*   28  2322     7518           8495           2        585  waiting      0 *
*   29  5028     8590           8761           2         79  waiting      0 *
*   32  2297    15248          15711           1        304  waiting      0 *
*   33  7083    15606             -1           0          0  ready        0 *
*****************************************************************************

CLOCK>  20430#*** WARNING: SIMCORE>
		Idle CPU with non-empty ready queue.



                       S I M C O R E   P C B   T A B L E 
*****************************************************************************
*  PCB  Size  Created  Last dispatch  Last burst  Accum CPU  Status   Prior *
*---------------------------------------------------------------------------*
*    9  2694     2307             -1           0          0  ready        0 *
*    1  5956      332            364           1          4  ready        0 *
*    5  2026      940             -1           0          0  ready        0 *
*   15  4938     4976           5271           2        155  ready        0 *
*   10  5846     2707             -1           0          0  ready        0 *
*   12  1599     3662             -1           0          0  ready        0 *
*   13  3219     3773             -1           0          0  ready        0 *
*   14  6536     4159             -1           0          0  ready        0 *
*   27  5593     7253           7320           1         18  ready        0 *
*   17  7940     5491             -1           0          0  ready        0 *
*   18  6460     5557             -1           0          0  ready        0 *
*   19  4361     5605             -1           0          0  ready        0 *
*   20  5809     5664             -1           0          0  ready        0 *
*   21  6582     5823             -1           0          0  ready        0 *
*   22  7582     5910             -1           0          0  ready        0 *
*   24  7858     6293             -1           0          0  ready        0 *
*   25  4333     6639             -1           0          0  ready        0 *
*   26   914     6663             -1           0          0  ready        0 *
*   28  2322     7518           8495           2        585  waiting      0 *
*   29  5028     8590           8761           2         79  waiting      0 *
*   32  2297    15248          15711           1        304  waiting      0 *
*   33  7083    15606             -1           0          0  ready        0 *
*****************************************************************************

CLOCK>  20431#*** WARNING: SIMCORE>
		Idle CPU with non-empty ready queue.



                       S I M C O R E   P C B   T A B L E 
*****************************************************************************
*  PCB  Size  Created  Last dispatch  Last burst  Accum CPU  Status   Prior *
*---------------------------------------------------------------------------*
*    9  2694     2307             -1           0          0  ready        0 *
*    1  5956      332            364           1          4  ready        0 *
*    5  2026      940             -1           0          0  ready        0 *
*   15  4938     4976           5271           2        155  ready        0 *
*   10  5846     2707             -1           0          0  ready        0 *
*   12  1599     3662             -1           0          0  ready        0 *
*   13  3219     3773             -1           0          0  ready        0 *
*   14  6536     4159             -1           0          0  ready        0 *
*   27  5593     7253           7320           1         18  ready        0 *
*   17  7940     5491             -1           0          0  ready        0 *
*   18  6460     5557             -1           0          0  ready        0 *
*   19  4361     5605             -1           0          0  ready        0 *
*   20  5809     5664             -1           0          0  ready        0 *
*   21  6582     5823             -1           0          0  ready        0 *
*   22  7582     5910             -1           0          0  ready        0 *
*   24  7858     6293             -1           0          0  ready        0 *
*   25  4333     6639             -1           0          0  ready        0 *
*   26   914     6663             -1           0          0  ready        0 *
*   28  2322     7518           8495           2        585  waiting      0 *
*   29  5028     8590           8761           2         79  waiting      0 *
*   32  2297    15248          15711           1        304  waiting      0 *
*   33  7083    15606             -1           0          0  ready        0 *
*****************************************************************************

CLOCK>  20432#*** WARNING: SIMCORE>
		Idle CPU with non-empty ready queue.



                       S I M C O R E   P C B   T A B L E 
*****************************************************************************
*  PCB  Size  Created  Last dispatch  Last burst  Accum CPU  Status   Prior *
*---------------------------------------------------------------------------*
*    9  2694     2307             -1           0          0  ready        0 *
*    1  5956      332            364           1          4  ready        0 *
*    5  2026      940             -1           0          0  ready        0 *
*   15  4938     4976           5271           2        155  ready        0 *
*   10  5846     2707             -1           0          0  ready        0 *
*   12  1599     3662             -1           0          0  ready        0 *
*   13  3219     3773             -1           0          0  ready        0 *
*   14  6536     4159             -1           0          0  ready        0 *
*   27  5593     7253           7320           1         18  ready        0 *
*   17  7940     5491             -1           0          0  ready        0 *
*   18  6460     5557             -1           0          0  ready        0 *
*   19  4361     5605             -1           0          0  ready        0 *
*   20  5809     5664             -1           0          0  ready        0 *
*   21  6582     5823             -1           0          0  ready        0 *
*   22  7582     5910             -1           0          0  ready        0 *
*   24  7858     6293             -1           0          0  ready        0 *
*   25  4333     6639             -1           0          0  ready        0 *
*   26   914     6663             -1           0          0  ready        0 *
*   28  2322     7518           8495           2        585  waiting      0 *
*   29  5028     8590           8761           2         79  waiting      0 *
*   32  2297    15248          15711           1        304  waiting      0 *
*   33  7083    15606             -1           0          0  ready        0 *
*****************************************************************************

CLOCK>  20433#*** WARNING: SIMCORE>
		Idle CPU with non-empty ready queue.



                       S I M C O R E   P C B   T A B L E 
*****************************************************************************
*  PCB  Size  Created  Last dispatch  Last burst  Accum CPU  Status   Prior *
*---------------------------------------------------------------------------*
*    9  2694     2307             -1           0          0  ready        0 *
*    1  5956      332            364           1          4  ready        0 *
*    5  2026      940             -1           0          0  ready        0 *
*   15  4938     4976           5271           2        155  ready        0 *
*   10  5846     2707             -1           0          0  ready        0 *
*   12  1599     3662             -1           0          0  ready        0 *
*   13  3219     3773             -1           0          0  ready        0 *
*   14  6536     4159             -1           0          0  ready        0 *
*   27  5593     7253           7320           1         18  ready        0 *
*   17  7940     5491             -1           0          0  ready        0 *
*   18  6460     5557             -1           0          0  ready        0 *
*   19  4361     5605             -1           0          0  ready        0 *
*   20  5809     5664             -1           0          0  ready        0 *
*   21  6582     5823             -1           0          0  ready        0 *
*   22  7582     5910             -1           0          0  ready        0 *
*   24  7858     6293             -1           0          0  ready        0 *
*   25  4333     6639             -1           0          0  ready        0 *
*   26   914     6663             -1           0          0  ready        0 *
*   28  2322     7518           8495           2        585  waiting      0 *
*   29  5028     8590           8761           2         79  waiting      0 *
*   32  2297    15248          15711           1        304  waiting      0 *
*   33  7083    15606             -1           0          0  ready        0 *
*****************************************************************************

CLOCK>  20434#*** WARNING: SIMCORE>
		Idle CPU with non-empty ready queue.



                       S I M C O R E   P C B   T A B L E 
*****************************************************************************
*  PCB  Size  Created  Last dispatch  Last burst  Accum CPU  Status   Prior *
*---------------------------------------------------------------------------*
*    9  2694     2307             -1           0          0  ready        0 *
*    1  5956      332            364           1          4  ready        0 *
*    5  2026      940             -1           0          0  ready        0 *
*   15  4938     4976           5271           2        155  ready        0 *
*   10  5846     2707             -1           0          0  ready        0 *
*   12  1599     3662             -1           0          0  ready        0 *
*   13  3219     3773             -1           0          0  ready        0 *
*   14  6536     4159             -1           0          0  ready        0 *
*   27  5593     7253           7320           1         18  ready        0 *
*   17  7940     5491             -1           0          0  ready        0 *
*   18  6460     5557             -1           0          0  ready        0 *
*   19  4361     5605             -1           0          0  ready        0 *
*   20  5809     5664             -1           0          0  ready        0 *
*   21  6582     5823             -1           0          0  ready        0 *
*   22  7582     5910             -1           0          0  ready        0 *
*   24  7858     6293             -1           0          0  ready        0 *
*   25  4333     6639             -1           0          0  ready        0 *
*   26   914     6663             -1           0          0  ready        0 *
*   28  2322     7518           8495           2        585  waiting      0 *
*   29  5028     8590           8761           2         79  waiting      0 *
*   32  2297    15248          15711           1        304  waiting      0 *
*   33  7083    15606             -1           0          0  ready        0 *
*****************************************************************************

CLOCK>  20435#*** WARNING: SIMCORE>
		Idle CPU with non-empty ready queue.



                       S I M C O R E   P C B   T A B L E 
*****************************************************************************
*  PCB  Size  Created  Last dispatch  Last burst  Accum CPU  Status   Prior *
*---------------------------------------------------------------------------*
*    9  2694     2307             -1           0          0  ready        0 *
*    1  5956      332            364           1          4  ready        0 *
*    5  2026      940             -1           0          0  ready        0 *
*   15  4938     4976           5271           2        155  ready        0 *
*   10  5846     2707             -1           0          0  ready        0 *
*   12  1599     3662             -1           0          0  ready        0 *
*   13  3219     3773             -1           0          0  ready        0 *
*   14  6536     4159             -1           0          0  ready        0 *
*   27  5593     7253           7320           1         18  ready        0 *
*   17  7940     5491             -1           0          0  ready        0 *
*   18  6460     5557             -1           0          0  ready        0 *
*   19  4361     5605             -1           0          0  ready        0 *
*   20  5809     5664             -1           0          0  ready        0 *
*   21  6582     5823             -1           0          0  ready        0 *
*   22  7582     5910             -1           0          0  ready        0 *
*   24  7858     6293             -1           0          0  ready        0 *
*   25  4333     6639             -1           0          0  ready        0 *
*   26   914     6663             -1           0          0  ready        0 *
*   28  2322     7518           8495           2        585  waiting      0 *
*   29  5028     8590           8761           2         79  waiting      0 *
*   32  2297    15248          15711           1        304  waiting      0 *
*   33  7083    15606             -1           0          0  ready        0 *
*****************************************************************************

CLOCK>  20436#*** WARNING: SIMCORE>
		Idle CPU with non-empty ready queue.



                       S I M C O R E   P C B   T A B L E 
*****************************************************************************
*  PCB  Size  Created  Last dispatch  Last burst  Accum CPU  Status   Prior *
*---------------------------------------------------------------------------*
*    9  2694     2307             -1           0          0  ready        0 *
*    1  5956      332            364           1          4  ready        0 *
*    5  2026      940             -1           0          0  ready        0 *
*   15  4938     4976           5271           2        155  ready        0 *
*   10  5846     2707             -1           0          0  ready        0 *
*   12  1599     3662             -1           0          0  ready        0 *
*   13  3219     3773             -1           0          0  ready        0 *
*   14  6536     4159             -1           0          0  ready        0 *
*   27  5593     7253           7320           1         18  ready        0 *
*   17  7940     5491             -1           0          0  ready        0 *
*   18  6460     5557             -1           0          0  ready        0 *
*   19  4361     5605             -1           0          0  ready        0 *
*   20  5809     5664             -1           0          0  ready        0 *
*   21  6582     5823             -1           0          0  ready        0 *
*   22  7582     5910             -1           0          0  ready        0 *
*   24  7858     6293             -1           0          0  ready        0 *
*   25  4333     6639             -1           0          0  ready        0 *
*   26   914     6663             -1           0          0  ready        0 *
*   28  2322     7518           8495           2        585  waiting      0 *
*   29  5028     8590           8761           2         79  waiting      0 *
*   32  2297    15248          15711           1        304  waiting      0 *
*   33  7083    15606             -1           0          0  ready        0 *
*****************************************************************************

CLOCK>  20437#*** WARNING: SIMCORE>
		Idle CPU with non-empty ready queue.



                       S I M C O R E   P C B   T A B L E 
*****************************************************************************
*  PCB  Size  Created  Last dispatch  Last burst  Accum CPU  Status   Prior *
*---------------------------------------------------------------------------*
*    9  2694     2307             -1           0          0  ready        0 *
*    1  5956      332            364           1          4  ready        0 *
*    5  2026      940             -1           0          0  ready        0 *
*   15  4938     4976           5271           2        155  ready        0 *
*   10  5846     2707             -1           0          0  ready        0 *
*   12  1599     3662             -1           0          0  ready        0 *
*   13  3219     3773             -1           0          0  ready        0 *
*   14  6536     4159             -1           0          0  ready        0 *
*   27  5593     7253           7320           1         18  ready        0 *
*   17  7940     5491             -1           0          0  ready        0 *
*   18  6460     5557             -1           0          0  ready        0 *
*   19  4361     5605             -1           0          0  ready        0 *
*   20  5809     5664             -1           0          0  ready        0 *
*   21  6582     5823             -1           0          0  ready        0 *
*   22  7582     5910             -1           0          0  ready        0 *
*   24  7858     6293             -1           0          0  ready        0 *
*   25  4333     6639             -1           0          0  ready        0 *
*   26   914     6663             -1           0          0  ready        0 *
*   28  2322     7518           8495           2        585  waiting      0 *
*   29  5028     8590           8761           2         79  waiting      0 *
*   32  2297    15248          15711           1        304  waiting      0 *
*   33  7083    15606             -1           0          0  ready        0 *
*****************************************************************************



	***  The following warning looks like a recurrent problem;
	***  it will be supressed till time = 30438.

CLOCK>  20438#*** WARNING: SIMCORE>
		Idle CPU with non-empty ready queue.



                       S I M C O R E   P C B   T A B L E 
*****************************************************************************
*  PCB  Size  Created  Last dispatch  Last burst  Accum CPU  Status   Prior *
*---------------------------------------------------------------------------*
*    9  2694     2307             -1           0          0  ready        0 *
*    1  5956      332            364           1          4  ready        0 *
*    5  2026      940             -1           0          0  ready        0 *
*   15  4938     4976           5271           2        155  ready        0 *
*   10  5846     2707             -1           0          0  ready        0 *
*   12  1599     3662             -1           0          0  ready        0 *
*   13  3219     3773             -1           0          0  ready        0 *
*   14  6536     4159             -1           0          0  ready        0 *
*   27  5593     7253           7320           1         18  ready        0 *
*   17  7940     5491             -1           0          0  ready        0 *
*   18  6460     5557             -1           0          0  ready        0 *
*   19  4361     5605             -1           0          0  ready        0 *
*   20  5809     5664             -1           0          0  ready        0 *
*   21  6582     5823             -1           0          0  ready        0 *
*   22  7582     5910             -1           0          0  ready        0 *
*   24  7858     6293             -1           0          0  ready        0 *
*   25  4333     6639             -1           0          0  ready        0 *
*   26   914     6663             -1           0          0  ready        0 *
*   28  2322     7518           8495           2        585  waiting      0 *
*   29  5028     8590           8761           2         79  waiting      0 *
*   32  2297    15248          15711           1        304  waiting      0 *
*   33  7083    15606             -1           0          0  ready        0 *
*****************************************************************************

CLOCK>  30000#*** WARNING: SIMCORE>
		PCB 9 is ready and starving for at least 7000 time units.
		Possible cause:
			- Due to error in CPU module,
			  was not inserted into ready queue.





                       S I M C O R E   P C B   T A B L E 
*****************************************************************************
*  PCB  Size  Created  Last dispatch  Last burst  Accum CPU  Status   Prior *
*---------------------------------------------------------------------------*
*    9  2694     2307             -1           0          0  ready        0 *
*    1  5956      332            364           1          4  ready        0 *
*    5  2026      940             -1           0          0  ready        0 *
*   15  4938     4976           5271           2        155  ready        0 *
*   10  5846     2707             -1           0          0  ready        0 *
*   12  1599     3662             -1           0          0  ready        0 *
*   13  3219     3773             -1           0          0  ready        0 *
*   14  6536     4159             -1           0          0  ready        0 *
*   27  5593     7253           7320           1         18  ready        0 *
*   17  7940     5491             -1           0          0  ready        0 *
*   18  6460     5557             -1           0          0  ready        0 *
*   19  4361     5605             -1           0          0  ready        0 *
*   20  5809     5664             -1           0          0  ready        0 *
*   21  6582     5823             -1           0          0  ready        0 *
*   22  7582     5910             -1           0          0  ready        0 *
*   24  7858     6293             -1           0          0  ready        0 *
*   25  4333     6639             -1           0          0  ready        0 *
*   26   914     6663             -1           0          0  ready        0 *
*   28  2322     7518           8495           2        585  waiting      0 *
*   29  5028     8590           8761           2         79  waiting      0 *
*   32  2297    15248          15711           1        304  waiting      0 *
*   33  7083    15606             -1           0          0  ready        0 *
*   34  1925    22134          22270           3         34  waiting      0 *
*   35  6002    28131          28285           1         42  waiting      0 *
*   36  1641    28318          28451           4         97  waiting      0 *
*   37  5391    29601          29724           1         35  waiting      0 *
*****************************************************************************



:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
::                                                               ::
::                  Snapshot at clock :  30000                   ::
::                                                               ::
:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::


              S I M C O R E   W A I T I N G   Q U E U E 
*****************************************************************************
* Event   PCB   IORB   File                  RRB    Rsrc   PRRB  SocketName *
*---------------------------------------------------------------------------*
*   470    32   none   none                  155       3   none  none       *
*   482    35   none   none                  159       3   none  none       *
*   491    36   none   none                  162       2   none  none       *
*   496    37   none   none                  165       3   none  none       *
*   407    28   none   none                 none    none      8  Xwindow    *
*   474    34   none   none                 none    none     10  coursework *
*   416    29   none   none                 none    none      9  talk.alt   *
*****************************************************************************



                       S I M C O R E   P C B   T A B L E 
*****************************************************************************
*  PCB  Size  Created  Last dispatch  Last burst  Accum CPU  Status   Prior *
*---------------------------------------------------------------------------*
*    9  2694     2307             -1           0          0  ready        0 *
*    1  5956      332            364           1          4  ready        0 *
*    5  2026      940             -1           0          0  ready        0 *
*   15  4938     4976           5271           2        155  ready        0 *
*   10  5846     2707             -1           0          0  ready        0 *
*   12  1599     3662             -1           0          0  ready        0 *
*   13  3219     3773             -1           0          0  ready        0 *
*   14  6536     4159             -1           0          0  ready        0 *
*   27  5593     7253           7320           1         18  ready        0 *
*   17  7940     5491             -1           0          0  ready        0 *
*   18  6460     5557             -1           0          0  ready        0 *
*   19  4361     5605             -1           0          0  ready        0 *
*   20  5809     5664             -1           0          0  ready        0 *
*   21  6582     5823             -1           0          0  ready        0 *
*   22  7582     5910             -1           0          0  ready        0 *
*   24  7858     6293             -1           0          0  ready        0 *
*   25  4333     6639             -1           0          0  ready        0 *
*   26   914     6663             -1           0          0  ready        0 *
*   28  2322     7518           8495           2        585  waiting      0 *
*   29  5028     8590           8761           2         79  waiting      0 *
*   32  2297    15248          15711           1        304  waiting      0 *
*   33  7083    15606             -1           0          0  ready        0 *
*   34  1925    22134          22270           3         34  waiting      0 *
*   35  6002    28131          28285           1         42  waiting      0 *
*   36  1641    28318          28451           4         97  waiting      0 *
*   37  5391    29601          29724           1         35  waiting      0 *
*****************************************************************************



=====================  Summary of Statistics  ====================

Total num of processes created                            =    38
  Total num of processes terminated                             =   11
  Total num of processes killed                                 =    1
        num of processes in CPU ready queue                     =   19
        num of processes in event waiting queues                =    7

  Total num of wait requests                               =  116
  Total num of signals                                     =  270
  Total num of timer interrupts                            =  578

CPU time used                                        =  1973
CPU utilization                                      =     0.0658

Memory utilization                                   =     0.8167

System throughput ( x 1000 )                         =     0.3667
Average num of processes during simulation           =    18.1809
Average CPU time per process                         =   259.6316
Average waiting time per process                     = 14298.0263
Average turnaround time per process                  = 14353.3421




CLOCK>  30439#*** WARNING: SIMCORE>
		Idle CPU with non-empty ready queue.



                       S I M C O R E   P C B   T A B L E 
*****************************************************************************
*  PCB  Size  Created  Last dispatch  Last burst  Accum CPU  Status   Prior *
*---------------------------------------------------------------------------*
*    9  2694     2307             -1           0          0  ready        0 *
*    1  5956      332            364           1          4  ready        0 *
*    5  2026      940             -1           0          0  ready        0 *
*   15  4938     4976           5271           2        155  ready        0 *
*   10  5846     2707             -1           0          0  ready        0 *
*   12  1599     3662             -1           0          0  ready        0 *
*   13  3219     3773             -1           0          0  ready        0 *
*   14  6536     4159             -1           0          0  ready        0 *
*   27  5593     7253           7320           1         18  ready        0 *
*   17  7940     5491             -1           0          0  ready        0 *
*   18  6460     5557             -1           0          0  ready        0 *
*   19  4361     5605             -1           0          0  ready        0 *
*   20  5809     5664             -1           0          0  ready        0 *
*   21  6582     5823             -1           0          0  ready        0 *
*   22  7582     5910             -1           0          0  ready        0 *
*   24  7858     6293             -1           0          0  ready        0 *
*   25  4333     6639             -1           0          0  ready        0 *
*   26   914     6663             -1           0          0  ready        0 *
*   28  2322     7518           8495           2        585  waiting      0 *
*   29  5028     8590           8761           2         79  waiting      0 *
*   32  2297    15248          15711           1        304  waiting      0 *
*   33  7083    15606             -1           0          0  ready        0 *
*   34  1925    22134          22270           3         34  waiting      0 *
*   35  6002    28131          28285           1         42  waiting      0 *
*   36  1641    28318          28451           4         97  waiting      0 *
*   37  5391    29601          29724           1         35  waiting      0 *
*****************************************************************************

CLOCK>  30440#*** WARNING: SIMCORE>
		Idle CPU with non-empty ready queue.



                       S I M C O R E   P C B   T A B L E 
*****************************************************************************
*  PCB  Size  Created  Last dispatch  Last burst  Accum CPU  Status   Prior *
*---------------------------------------------------------------------------*
*    9  2694     2307             -1           0          0  ready        0 *
*    1  5956      332            364           1          4  ready        0 *
*    5  2026      940             -1           0          0  ready        0 *
*   15  4938     4976           5271           2        155  ready        0 *
*   10  5846     2707             -1           0          0  ready        0 *
*   12  1599     3662             -1           0          0  ready        0 *
*   13  3219     3773             -1           0          0  ready        0 *
*   14  6536     4159             -1           0          0  ready        0 *
*   27  5593     7253           7320           1         18  ready        0 *
*   17  7940     5491             -1           0          0  ready        0 *
*   18  6460     5557             -1           0          0  ready        0 *
*   19  4361     5605             -1           0          0  ready        0 *
*   20  5809     5664             -1           0          0  ready        0 *
*   21  6582     5823             -1           0          0  ready        0 *
*   22  7582     5910             -1           0          0  ready        0 *
*   24  7858     6293             -1           0          0  ready        0 *
*   25  4333     6639             -1           0          0  ready        0 *
*   26   914     6663             -1           0          0  ready        0 *
*   28  2322     7518           8495           2        585  waiting      0 *
*   29  5028     8590           8761           2         79  waiting      0 *
*   32  2297    15248          15711           1        304  waiting      0 *
*   33  7083    15606             -1           0          0  ready        0 *
*   34  1925    22134          22270           3         34  waiting      0 *
*   35  6002    28131          28285           1         42  waiting      0 *
*   36  1641    28318          28451           4         97  waiting      0 *
*   37  5391    29601          29724           1         35  waiting      0 *
*****************************************************************************

CLOCK>  30441#*** WARNING: SIMCORE>
		Idle CPU with non-empty ready queue.



                       S I M C O R E   P C B   T A B L E 
*****************************************************************************
*  PCB  Size  Created  Last dispatch  Last burst  Accum CPU  Status   Prior *
*---------------------------------------------------------------------------*
*    9  2694     2307             -1           0          0  ready        0 *
*    1  5956      332            364           1          4  ready        0 *
*    5  2026      940             -1           0          0  ready        0 *
*   15  4938     4976           5271           2        155  ready        0 *
*   10  5846     2707             -1           0          0  ready        0 *
*   12  1599     3662             -1           0          0  ready        0 *
*   13  3219     3773             -1           0          0  ready        0 *
*   14  6536     4159             -1           0          0  ready        0 *
*   27  5593     7253           7320           1         18  ready        0 *
*   17  7940     5491             -1           0          0  ready        0 *
*   18  6460     5557             -1           0          0  ready        0 *
*   19  4361     5605             -1           0          0  ready        0 *
*   20  5809     5664             -1           0          0  ready        0 *
*   21  6582     5823             -1           0          0  ready        0 *
*   22  7582     5910             -1           0          0  ready        0 *
*   24  7858     6293             -1           0          0  ready        0 *
*   25  4333     6639             -1           0          0  ready        0 *
*   26   914     6663             -1           0          0  ready        0 *
*   28  2322     7518           8495           2        585  waiting      0 *
*   29  5028     8590           8761           2         79  waiting      0 *
*   32  2297    15248          15711           1        304  waiting      0 *
*   33  7083    15606             -1           0          0  ready        0 *
*   34  1925    22134          22270           3         34  waiting      0 *
*   35  6002    28131          28285           1         42  waiting      0 *
*   36  1641    28318          28451           4         97  waiting      0 *
*   37  5391    29601          29724           1         35  waiting      0 *
*****************************************************************************

CLOCK>  30442#*** WARNING: SIMCORE>
		Idle CPU with non-empty ready queue.



                       S I M C O R E   P C B   T A B L E 
*****************************************************************************
*  PCB  Size  Created  Last dispatch  Last burst  Accum CPU  Status   Prior *
*---------------------------------------------------------------------------*
*    9  2694     2307             -1           0          0  ready        0 *
*    1  5956      332            364           1          4  ready        0 *
*    5  2026      940             -1           0          0  ready        0 *
*   15  4938     4976           5271           2        155  ready        0 *
*   10  5846     2707             -1           0          0  ready        0 *
*   12  1599     3662             -1           0          0  ready        0 *
*   13  3219     3773             -1           0          0  ready        0 *
*   14  6536     4159             -1           0          0  ready        0 *
*   27  5593     7253           7320           1         18  ready        0 *
*   17  7940     5491             -1           0          0  ready        0 *
*   18  6460     5557             -1           0          0  ready        0 *
*   19  4361     5605             -1           0          0  ready        0 *
*   20  5809     5664             -1           0          0  ready        0 *
*   21  6582     5823             -1           0          0  ready        0 *
*   22  7582     5910             -1           0          0  ready        0 *
*   24  7858     6293             -1           0          0  ready        0 *
*   25  4333     6639             -1           0          0  ready        0 *
*   26   914     6663             -1           0          0  ready        0 *
*   28  2322     7518           8495           2        585  waiting      0 *
*   29  5028     8590           8761           2         79  waiting      0 *
*   32  2297    15248          15711           1        304  waiting      0 *
*   33  7083    15606             -1           0          0  ready        0 *
*   34  1925    22134          22270           3         34  waiting      0 *
*   35  6002    28131          28285           1         42  waiting      0 *
*   36  1641    28318          28451           4         97  waiting      0 *
*   37  5391    29601          29724           1         35  waiting      0 *
*****************************************************************************

CLOCK>  30443#*** WARNING: SIMCORE>
		Idle CPU with non-empty ready queue.



                       S I M C O R E   P C B   T A B L E 
*****************************************************************************
*  PCB  Size  Created  Last dispatch  Last burst  Accum CPU  Status   Prior *
*---------------------------------------------------------------------------*
*    9  2694     2307             -1           0          0  ready        0 *
*    1  5956      332            364           1          4  ready        0 *
*    5  2026      940             -1           0          0  ready        0 *
*   15  4938     4976           5271           2        155  ready        0 *
*   10  5846     2707             -1           0          0  ready        0 *
*   12  1599     3662             -1           0          0  ready        0 *
*   13  3219     3773             -1           0          0  ready        0 *
*   14  6536     4159             -1           0          0  ready        0 *
*   27  5593     7253           7320           1         18  ready        0 *
*   17  7940     5491             -1           0          0  ready        0 *
*   18  6460     5557             -1           0          0  ready        0 *
*   19  4361     5605             -1           0          0  ready        0 *
*   20  5809     5664             -1           0          0  ready        0 *
*   21  6582     5823             -1           0          0  ready        0 *
*   22  7582     5910             -1           0          0  ready        0 *
*   24  7858     6293             -1           0          0  ready        0 *
*   25  4333     6639             -1           0          0  ready        0 *
*   26   914     6663             -1           0          0  ready        0 *
*   28  2322     7518           8495           2        585  waiting      0 *
*   29  5028     8590           8761           2         79  waiting      0 *
*   32  2297    15248          15711           1        304  waiting      0 *
*   33  7083    15606             -1           0          0  ready        0 *
*   34  1925    22134          22270           3         34  waiting      0 *
*   35  6002    28131          28285           1         42  waiting      0 *
*   36  1641    28318          28451           4         97  waiting      0 *
*   37  5391    29601          29724           1         35  waiting      0 *
*****************************************************************************

CLOCK>  30444#*** WARNING: SIMCORE>
		Idle CPU with non-empty ready queue.



                       S I M C O R E   P C B   T A B L E 
*****************************************************************************
*  PCB  Size  Created  Last dispatch  Last burst  Accum CPU  Status   Prior *
*---------------------------------------------------------------------------*
*    9  2694     2307             -1           0          0  ready        0 *
*    1  5956      332            364           1          4  ready        0 *
*    5  2026      940             -1           0          0  ready        0 *
*   15  4938     4976           5271           2        155  ready        0 *
*   10  5846     2707             -1           0          0  ready        0 *
*   12  1599     3662             -1           0          0  ready        0 *
*   13  3219     3773             -1           0          0  ready        0 *
*   14  6536     4159             -1           0          0  ready        0 *
*   27  5593     7253           7320           1         18  ready        0 *
*   17  7940     5491             -1           0          0  ready        0 *
*   18  6460     5557             -1           0          0  ready        0 *
*   19  4361     5605             -1           0          0  ready        0 *
*   20  5809     5664             -1           0          0  ready        0 *
*   21  6582     5823             -1           0          0  ready        0 *
*   22  7582     5910             -1           0          0  ready        0 *
*   24  7858     6293             -1           0          0  ready        0 *
*   25  4333     6639             -1           0          0  ready        0 *
*   26   914     6663             -1           0          0  ready        0 *
*   28  2322     7518           8495           2        585  waiting      0 *
*   29  5028     8590           8761           2         79  waiting      0 *
*   32  2297    15248          15711           1        304  waiting      0 *
*   33  7083    15606             -1           0          0  ready        0 *
*   34  1925    22134          22270           3         34  waiting      0 *
*   35  6002    28131          28285           1         42  waiting      0 *
*   36  1641    28318          28451           4         97  waiting      0 *
*   37  5391    29601          29724           1         35  waiting      0 *
*****************************************************************************

CLOCK>  30445#*** WARNING: SIMCORE>
		Idle CPU with non-empty ready queue.



                       S I M C O R E   P C B   T A B L E 
*****************************************************************************
*  PCB  Size  Created  Last dispatch  Last burst  Accum CPU  Status   Prior *
*---------------------------------------------------------------------------*
*    9  2694     2307             -1           0          0  ready        0 *
*    1  5956      332            364           1          4  ready        0 *
*    5  2026      940             -1           0          0  ready        0 *
*   15  4938     4976           5271           2        155  ready        0 *
*   10  5846     2707             -1           0          0  ready        0 *
*   12  1599     3662             -1           0          0  ready        0 *
*   13  3219     3773             -1           0          0  ready        0 *
*   14  6536     4159             -1           0          0  ready        0 *
*   27  5593     7253           7320           1         18  ready        0 *
*   17  7940     5491             -1           0          0  ready        0 *
*   18  6460     5557             -1           0          0  ready        0 *
*   19  4361     5605             -1           0          0  ready        0 *
*   20  5809     5664             -1           0          0  ready        0 *
*   21  6582     5823             -1           0          0  ready        0 *
*   22  7582     5910             -1           0          0  ready        0 *
*   24  7858     6293             -1           0          0  ready        0 *
*   25  4333     6639             -1           0          0  ready        0 *
*   26   914     6663             -1           0          0  ready        0 *
*   28  2322     7518           8495           2        585  waiting      0 *
*   29  5028     8590           8761           2         79  waiting      0 *
*   32  2297    15248          15711           1        304  waiting      0 *
*   33  7083    15606             -1           0          0  ready        0 *
*   34  1925    22134          22270           3         34  waiting      0 *
*   35  6002    28131          28285           1         42  waiting      0 *
*   36  1641    28318          28451           4         97  waiting      0 *
*   37  5391    29601          29724           1         35  waiting      0 *
*****************************************************************************

CLOCK>  30446#*** WARNING: SIMCORE>
		Idle CPU with non-empty ready queue.



                       S I M C O R E   P C B   T A B L E 
*****************************************************************************
*  PCB  Size  Created  Last dispatch  Last burst  Accum CPU  Status   Prior *
*---------------------------------------------------------------------------*
*    9  2694     2307             -1           0          0  ready        0 *
*    1  5956      332            364           1          4  ready        0 *
*    5  2026      940             -1           0          0  ready        0 *
*   15  4938     4976           5271           2        155  ready        0 *
*   10  5846     2707             -1           0          0  ready        0 *
*   12  1599     3662             -1           0          0  ready        0 *
*   13  3219     3773             -1           0          0  ready        0 *
*   14  6536     4159             -1           0          0  ready        0 *
*   27  5593     7253           7320           1         18  ready        0 *
*   17  7940     5491             -1           0          0  ready        0 *
*   18  6460     5557             -1           0          0  ready        0 *
*   19  4361     5605             -1           0          0  ready        0 *
*   20  5809     5664             -1           0          0  ready        0 *
*   21  6582     5823             -1           0          0  ready        0 *
*   22  7582     5910             -1           0          0  ready        0 *
*   24  7858     6293             -1           0          0  ready        0 *
*   25  4333     6639             -1           0          0  ready        0 *
*   26   914     6663             -1           0          0  ready        0 *
*   28  2322     7518           8495           2        585  waiting      0 *
*   29  5028     8590           8761           2         79  waiting      0 *
*   32  2297    15248          15711           1        304  waiting      0 *
*   33  7083    15606             -1           0          0  ready        0 *
*   34  1925    22134          22270           3         34  waiting      0 *
*   35  6002    28131          28285           1         42  waiting      0 *
*   36  1641    28318          28451           4         97  waiting      0 *
*   37  5391    29601          29724           1         35  waiting      0 *
*****************************************************************************

CLOCK>  30447#*** WARNING: SIMCORE>
		Idle CPU with non-empty ready queue.



                       S I M C O R E   P C B   T A B L E 
*****************************************************************************
*  PCB  Size  Created  Last dispatch  Last burst  Accum CPU  Status   Prior *
*---------------------------------------------------------------------------*
*    9  2694     2307             -1           0          0  ready        0 *
*    1  5956      332            364           1          4  ready        0 *
*    5  2026      940             -1           0          0  ready        0 *
*   15  4938     4976           5271           2        155  ready        0 *
*   10  5846     2707             -1           0          0  ready        0 *
*   12  1599     3662             -1           0          0  ready        0 *
*   13  3219     3773             -1           0          0  ready        0 *
*   14  6536     4159             -1           0          0  ready        0 *
*   27  5593     7253           7320           1         18  ready        0 *
*   17  7940     5491             -1           0          0  ready        0 *
*   18  6460     5557             -1           0          0  ready        0 *
*   19  4361     5605             -1           0          0  ready        0 *
*   20  5809     5664             -1           0          0  ready        0 *
*   21  6582     5823             -1           0          0  ready        0 *
*   22  7582     5910             -1           0          0  ready        0 *
*   24  7858     6293             -1           0          0  ready        0 *
*   25  4333     6639             -1           0          0  ready        0 *
*   26   914     6663             -1           0          0  ready        0 *
*   28  2322     7518           8495           2        585  waiting      0 *
*   29  5028     8590           8761           2         79  waiting      0 *
*   32  2297    15248          15711           1        304  waiting      0 *
*   33  7083    15606             -1           0          0  ready        0 *
*   34  1925    22134          22270           3         34  waiting      0 *
*   35  6002    28131          28285           1         42  waiting      0 *
*   36  1641    28318          28451           4         97  waiting      0 *
*   37  5391    29601          29724           1         35  waiting      0 *
*****************************************************************************

CLOCK>  30448#*** WARNING: SIMCORE>
		Idle CPU with non-empty ready queue.



                       S I M C O R E   P C B   T A B L E 
*****************************************************************************
*  PCB  Size  Created  Last dispatch  Last burst  Accum CPU  Status   Prior *
*---------------------------------------------------------------------------*
*    9  2694     2307             -1           0          0  ready        0 *
*    1  5956      332            364           1          4  ready        0 *
*    5  2026      940             -1           0          0  ready        0 *
*   15  4938     4976           5271           2        155  ready        0 *
*   10  5846     2707             -1           0          0  ready        0 *
*   12  1599     3662             -1           0          0  ready        0 *
*   13  3219     3773             -1           0          0  ready        0 *
*   14  6536     4159             -1           0          0  ready        0 *
*   27  5593     7253           7320           1         18  ready        0 *
*   17  7940     5491             -1           0          0  ready        0 *
*   18  6460     5557             -1           0          0  ready        0 *
*   19  4361     5605             -1           0          0  ready        0 *
*   20  5809     5664             -1           0          0  ready        0 *
*   21  6582     5823             -1           0          0  ready        0 *
*   22  7582     5910             -1           0          0  ready        0 *
*   24  7858     6293             -1           0          0  ready        0 *
*   25  4333     6639             -1           0          0  ready        0 *
*   26   914     6663             -1           0          0  ready        0 *
*   28  2322     7518           8495           2        585  waiting      0 *
*   29  5028     8590           8761           2         79  waiting      0 *
*   32  2297    15248          15711           1        304  waiting      0 *
*   33  7083    15606             -1           0          0  ready        0 *
*   34  1925    22134          22270           3         34  waiting      0 *
*   35  6002    28131          28285           1         42  waiting      0 *
*   36  1641    28318          28451           4         97  waiting      0 *
*   37  5391    29601          29724           1         35  waiting      0 *
*****************************************************************************



	***  The following warning looks like a recurrent problem;
	***  it will be supressed till time = 40449.

CLOCK>  30449#*** WARNING: SIMCORE>
		Idle CPU with non-empty ready queue.



                       S I M C O R E   P C B   T A B L E 
*****************************************************************************
*  PCB  Size  Created  Last dispatch  Last burst  Accum CPU  Status   Prior *
*---------------------------------------------------------------------------*
*    9  2694     2307             -1           0          0  ready        0 *
*    1  5956      332            364           1          4  ready        0 *
*    5  2026      940             -1           0          0  ready        0 *
*   15  4938     4976           5271           2        155  ready        0 *
*   10  5846     2707             -1           0          0  ready        0 *
*   12  1599     3662             -1           0          0  ready        0 *
*   13  3219     3773             -1           0          0  ready        0 *
*   14  6536     4159             -1           0          0  ready        0 *
*   27  5593     7253           7320           1         18  ready        0 *
*   17  7940     5491             -1           0          0  ready        0 *
*   18  6460     5557             -1           0          0  ready        0 *
*   19  4361     5605             -1           0          0  ready        0 *
*   20  5809     5664             -1           0          0  ready        0 *
*   21  6582     5823             -1           0          0  ready        0 *
*   22  7582     5910             -1           0          0  ready        0 *
*   24  7858     6293             -1           0          0  ready        0 *
*   25  4333     6639             -1           0          0  ready        0 *
*   26   914     6663             -1           0          0  ready        0 *
*   28  2322     7518           8495           2        585  waiting      0 *
*   29  5028     8590           8761           2         79  waiting      0 *
*   32  2297    15248          15711           1        304  waiting      0 *
*   33  7083    15606             -1           0          0  ready        0 *
*   34  1925    22134          22270           3         34  waiting      0 *
*   35  6002    28131          28285           1         42  waiting      0 *
*   36  1641    28318          28451           4         97  waiting      0 *
*   37  5391    29601          29724           1         35  waiting      0 *
*****************************************************************************

CLOCK>  40000#*** WARNING: SIMCORE>
		PCB 9 is ready and starving for at least 7000 time units.
		Possible cause:
			- Due to error in CPU module,
			  was not inserted into ready queue.





                       S I M C O R E   P C B   T A B L E 
*****************************************************************************
*  PCB  Size  Created  Last dispatch  Last burst  Accum CPU  Status   Prior *
*---------------------------------------------------------------------------*
*    9  2694     2307             -1           0          0  ready        0 *
*    1  5956      332            364           1          4  ready        0 *
*    5  2026      940             -1           0          0  ready        0 *
*   15  4938     4976           5271           2        155  ready        0 *
*   10  5846     2707             -1           0          0  ready        0 *
*   12  1599     3662             -1           0          0  ready        0 *
*   13  3219     3773             -1           0          0  ready        0 *
*   14  6536     4159             -1           0          0  ready        0 *
*   27  5593     7253           7320           1         18  ready        0 *
*   17  7940     5491             -1           0          0  ready        0 *
*   18  6460     5557             -1           0          0  ready        0 *
*   19  4361     5605             -1           0          0  ready        0 *
*   20  5809     5664             -1           0          0  ready        0 *
*   21  6582     5823             -1           0          0  ready        0 *
*   22  7582     5910             -1           0          0  ready        0 *
*   24  7858     6293             -1           0          0  ready        0 *
*   25  4333     6639             -1           0          0  ready        0 *
*   26   914     6663             -1           0          0  ready        0 *
*   28  2322     7518           8495           2        585  waiting      0 *
*   29  5028     8590           8761           2         79  waiting      0 *
*   32  2297    15248          15711           1        304  waiting      0 *
*   33  7083    15606             -1           0          0  ready        0 *
*   34  1925    22134          22270           3         34  waiting      0 *
*   35  6002    28131          28285           1         42  waiting      0 *
*   36  1641    28318          28451           4         97  waiting      0 *
*   37  5391    29601          29724           1         35  waiting      0 *
*   38  1863    31483          31562           1         30  waiting      0 *
*   39  3273    36966          37339           1        161  waiting      0 *
*****************************************************************************



:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
::                                                               ::
::                  Snapshot at clock :  40000                   ::
::                                                               ::
:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::


              S I M C O R E   W A I T I N G   Q U E U E 
*****************************************************************************
* Event   PCB   IORB   File                  RRB    Rsrc   PRRB  SocketName *
*---------------------------------------------------------------------------*
*   470    32   none   none                  155       3   none  none       *
*   482    35   none   none                  159       3   none  none       *
*   491    36   none   none                  162       2   none  none       *
*   496    37   none   none                  165       3   none  none       *
*   502    38   none   none                  166       2   none  none       *
*   528    39   none   none                  169       3   none  none       *
*   407    28   none   none                 none    none      8  Xwindow    *
*   474    34   none   none                 none    none     10  coursework *
*   416    29   none   none                 none    none      9  talk.alt   *
*****************************************************************************



                       S I M C O R E   P C B   T A B L E 
*****************************************************************************
*  PCB  Size  Created  Last dispatch  Last burst  Accum CPU  Status   Prior *
*---------------------------------------------------------------------------*
*    9  2694     2307             -1           0          0  ready        0 *
*    1  5956      332            364           1          4  ready        0 *
*    5  2026      940             -1           0          0  ready        0 *
*   15  4938     4976           5271           2        155  ready        0 *
*   10  5846     2707             -1           0          0  ready        0 *
*   12  1599     3662             -1           0          0  ready        0 *
*   13  3219     3773             -1           0          0  ready        0 *
*   14  6536     4159             -1           0          0  ready        0 *
*   27  5593     7253           7320           1         18  ready        0 *
*   17  7940     5491             -1           0          0  ready        0 *
*   18  6460     5557             -1           0          0  ready        0 *
*   19  4361     5605             -1           0          0  ready        0 *
*   20  5809     5664             -1           0          0  ready        0 *
*   21  6582     5823             -1           0          0  ready        0 *
*   22  7582     5910             -1           0          0  ready        0 *
*   24  7858     6293             -1           0          0  ready        0 *
*   25  4333     6639             -1           0          0  ready        0 *
*   26   914     6663             -1           0          0  ready        0 *
*   28  2322     7518           8495           2        585  waiting      0 *
*   29  5028     8590           8761           2         79  waiting      0 *
*   32  2297    15248          15711           1        304  waiting      0 *
*   33  7083    15606             -1           0          0  ready        0 *
*   34  1925    22134          22270           3         34  waiting      0 *
*   35  6002    28131          28285           1         42  waiting      0 *
*   36  1641    28318          28451           4         97  waiting      0 *
*   37  5391    29601          29724           1         35  waiting      0 *
*   38  1863    31483          31562           1         30  waiting      0 *
*   39  3273    36966          37339           1        161  waiting      0 *
*****************************************************************************



=====================  Summary of Statistics  ====================

Total num of processes created                            =    40
  Total num of processes terminated                             =   11
  Total num of processes killed                                 =    1
        num of processes in CPU ready queue                     =   19
        num of processes in event waiting queues                =    9

  Total num of wait requests                               =  129
  Total num of signals                                     =  294
  Total num of timer interrupts                            =  603

CPU time used                                        =  2090
CPU utilization                                      =     0.0522

Memory utilization                                   =     0.8625

System throughput ( x 1000 )                         =     0.2750
Average num of processes during simulation           =    20.4245
Average CPU time per process                         =   275.0000
Average waiting time per process                     = 20368.7000
Average turnaround time per process                  = 20424.4500







====================     End of Simulation     ====================


CLOCK>  40000#*** WARNING: SIMCORE>
		PCB 9 is ready and starving for at least 7000 time units.
		Possible cause:
			- Due to error in CPU module,
			  was not inserted into ready queue.





                       S I M C O R E   P C B   T A B L E 
*****************************************************************************
*  PCB  Size  Created  Last dispatch  Last burst  Accum CPU  Status   Prior *
*---------------------------------------------------------------------------*
*    9  2694     2307             -1           0          0  ready        0 *
*    1  5956      332            364           1          4  ready        0 *
*    5  2026      940             -1           0          0  ready        0 *
*   15  4938     4976           5271           2        155  ready        0 *
*   10  5846     2707             -1           0          0  ready        0 *
*   12  1599     3662             -1           0          0  ready        0 *
*   13  3219     3773             -1           0          0  ready        0 *
*   14  6536     4159             -1           0          0  ready        0 *
*   27  5593     7253           7320           1         18  ready        0 *
*   17  7940     5491             -1           0          0  ready        0 *
*   18  6460     5557             -1           0          0  ready        0 *
*   19  4361     5605             -1           0          0  ready        0 *
*   20  5809     5664             -1           0          0  ready        0 *
*   21  6582     5823             -1           0          0  ready        0 *
*   22  7582     5910             -1           0          0  ready        0 *
*   24  7858     6293             -1           0          0  ready        0 *
*   25  4333     6639             -1           0          0  ready        0 *
*   26   914     6663             -1           0          0  ready        0 *
*   28  2322     7518           8495           2        585  waiting      0 *
*   29  5028     8590           8761           2         79  waiting      0 *
*   32  2297    15248          15711           1        304  waiting      0 *
*   33  7083    15606             -1           0          0  ready        0 *
*   34  1925    22134          22270           3         34  waiting      0 *
*   35  6002    28131          28285           1         42  waiting      0 *
*   36  1641    28318          28451           4         97  waiting      0 *
*   37  5391    29601          29724           1         35  waiting      0 *
*   38  1863    31483          31562           1         30  waiting      0 *
*   39  3273    36966          37339           1        161  waiting      0 *
*****************************************************************************



:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
::                                                               ::
::                  Snapshot at clock :  40000                   ::
::                                                               ::
:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::


              S I M C O R E   W A I T I N G   Q U E U E 
*****************************************************************************
* Event   PCB   IORB   File                  RRB    Rsrc   PRRB  SocketName *
*---------------------------------------------------------------------------*
*   470    32   none   none                  155       3   none  none       *
*   482    35   none   none                  159       3   none  none       *
*   491    36   none   none                  162       2   none  none       *
*   496    37   none   none                  165       3   none  none       *
*   502    38   none   none                  166       2   none  none       *
*   528    39   none   none                  169       3   none  none       *
*   407    28   none   none                 none    none      8  Xwindow    *
*   474    34   none   none                 none    none     10  coursework *
*   416    29   none   none                 none    none      9  talk.alt   *
*****************************************************************************



                       S I M C O R E   P C B   T A B L E 
*****************************************************************************
*  PCB  Size  Created  Last dispatch  Last burst  Accum CPU  Status   Prior *
*---------------------------------------------------------------------------*
*    9  2694     2307             -1           0          0  ready        0 *
*    1  5956      332            364           1          4  ready        0 *
*    5  2026      940             -1           0          0  ready        0 *
*   15  4938     4976           5271           2        155  ready        0 *
*   10  5846     2707             -1           0          0  ready        0 *
*   12  1599     3662             -1           0          0  ready        0 *
*   13  3219     3773             -1           0          0  ready        0 *
*   14  6536     4159             -1           0          0  ready        0 *
*   27  5593     7253           7320           1         18  ready        0 *
*   17  7940     5491             -1           0          0  ready        0 *
*   18  6460     5557             -1           0          0  ready        0 *
*   19  4361     5605             -1           0          0  ready        0 *
*   20  5809     5664             -1           0          0  ready        0 *
*   21  6582     5823             -1           0          0  ready        0 *
*   22  7582     5910             -1           0          0  ready        0 *
*   24  7858     6293             -1           0          0  ready        0 *
*   25  4333     6639             -1           0          0  ready        0 *
*   26   914     6663             -1           0          0  ready        0 *
*   28  2322     7518           8495           2        585  waiting      0 *
*   29  5028     8590           8761           2         79  waiting      0 *
*   32  2297    15248          15711           1        304  waiting      0 *
*   33  7083    15606             -1           0          0  ready        0 *
*   34  1925    22134          22270           3         34  waiting      0 *
*   35  6002    28131          28285           1         42  waiting      0 *
*   36  1641    28318          28451           4         97  waiting      0 *
*   37  5391    29601          29724           1         35  waiting      0 *
*   38  1863    31483          31562           1         30  waiting      0 *
*   39  3273    36966          37339           1        161  waiting      0 *
*****************************************************************************



=====================  Summary of Statistics  ====================

Total num of processes created                            =    40
  Total num of processes terminated                             =   11
  Total num of processes killed                                 =    1
        num of processes in CPU ready queue                     =   19
        num of processes in event waiting queues                =    9

  Total num of wait requests                               =  129
  Total num of signals                                     =  294
  Total num of timer interrupts                            =  603

CPU time used                                        =  2090
CPU utilization                                      =     0.0522

Memory utilization                                   =     0.8625

System throughput ( x 1000 )                         =     0.2750
Average num of processes during simulation           =    20.4245
Average CPU time per process                         =   275.0000
Average waiting time per process                     = 20368.7000
Average turnaround time per process                  = 20424.4500




